apiVersion: v1
kind: Secret
metadata:
  name: minipay-secrets
  namespace: minipay
type: Opaque
data:
  POSTGRES_PASSWORD: bWluaXBheQ==
  API_KEY: ZGV2LWxvY2FsLWtleQ==
  DATABASE_URL: cG9zdGdyZXNxbCtwc3ljb3BnOi8vbWluaXBheTptaW5pcGF5QG1pbmlwYXktZGI6NTQzMi9taW5pcGF5
